# Generated by Django 4.2 on 2024-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=300, null=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='preview')),
                ('date_created', models.DateField(verbose_name='date_created')),
                ('view_count', models.IntegerField(default=0, verbose_name='view_count')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
