# Generated by Django 4.2 on 2024-01-26 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_create'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='change_data',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='change_data'),
        ),
    ]
