# Generated by Django 4.2 on 2024-01-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_product_active', 'Can set product active')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
