# Generated by Django 4.2 on 2024-01-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_product_active', 'Can set product active'), ('set_category', 'Can set category'), ('set_description', 'Can set description')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
